### ISSUE TITLE
Clarify Error Messages for Type Validation

### ISSUE THREAD

**Issue by torischuyler** [domainic/domainic#163]
## Describe the Bug

I was testing the username validation with constraints like being lowercase, alphanumeric, not matching `/^admin/i`, and within a size range of 3-20. The error message I received was confusing:

```
Expected String(being lower case, 
being only alphanumeric characters, 
matching /^admin/i, 
having size greater than 3 and less than 20), 

but got String(being not lower case, 
does not match /^admin/i) (TypeError)
```

This message suggests the string should match `/^admin/i` when it should not.

## To Reproduce

1.  Define a username validation with the following constraints:
```
username = _String
  .being_lowercase
  .being_alphanumeric
  .having_size_between(3, 20)
  .not_matching(/^admin/i)
```

2. Attempt to validate "Admin":
`username.validate!("Admin")`

## Expected Behavior

A clear and concise error message could be:
```
Expected String(being lowercase, 
alphanumeric, 
**not** matching /^admin/i, 
size 3-20), 

got String(not lowercase, **matches** /^admin/i)
```

## Environment

* Ruby version: `ruby 3.3.6`
* Gem name and version: `domainic-type 0.1.0.alpha.3.3.0`
* OS: MacOS

## Additional Context

Haven't pinpointed the exact location in the codebase to fix error message

**Comment by torischuyler** [comment]
@aaronmallen closing this, added my feedback [here](https://github.com/domainic/domainic/issues/132#issuecomment-2564180733)

**Comment by aaronmallen** [comment]
> @aaronmallen closing this, added my feedback [here](https://github.com/domainic/domainic/issues/132#issuecomment-2564180733)

I'm reopening as this is a legitimate bug, but please continue to leave other feedback like this on the other ticket.
